#!/usr/bin/env bash
# PID 1 for the omp container.
#
#   as root : align the `omp` user with PUID/PGID so files written into the
#             /workspace bind mount are owned correctly on the host, then drop
#             privileges and re-exec this same script.
#   as omp  : write models.yml from the environment, start a detached tmux
#             server running the agent, and block.
set -euo pipefail

STATE_DIR="${OMP_STATE_DIR:-/home/omp/.omp}"
AGENT_DIR="${STATE_DIR}/agent"
SESSION="${OMP_TMUX_SESSION:-omp}"

log() { printf '[omp-entrypoint] %s\n' "$*" >&2; }

if [ "$(id -u)" = "0" ]; then
    PUID="${PUID:-1000}"
    PGID="${PGID:-1000}"

    if [ "$(id -g omp)" != "$PGID" ]; then
        log "setting omp gid -> ${PGID}"
        groupmod -o -g "$PGID" omp
    fi
    if [ "$(id -u omp)" != "$PUID" ]; then
        log "setting omp uid -> ${PUID}"
        usermod -o -u "$PUID" omp
    fi

    # Only ever chown what we own. Never recurse into /workspace: it is a host
    # bind mount and chowning it would be both slow and destructive.
    mkdir -p "$HOME/tmp" "$HOME/.cache/bun" "$AGENT_DIR"
    chown -R "$PUID:$PGID" "$HOME"
    chown "$PUID:$PGID" /workspace 2>/dev/null || true

    log "dropping to uid=${PUID} gid=${PGID}"
    exec setpriv --reuid="$PUID" --regid="$PGID" --init-groups -- "$0" "$@"
fi

mkdir -p "$HOME/tmp" "$HOME/.cache/bun" "$AGENT_DIR"

# Bind-mounted repos usually have foreign ownership relative to the container
# user; without this every git call fails the dubious-ownership check.
git config --global --add safe.directory '*' 2>/dev/null || true
[ -n "${GIT_AUTHOR_NAME:-}" ] && git config --global user.name "${GIT_AUTHOR_NAME}"
[ -n "${GIT_AUTHOR_EMAIL:-}" ] && git config --global user.email "${GIT_AUTHOR_EMAIL}"

# ---------------------------------------------------------------------------
# models.yml, templated from the environment on every boot so that changing the
# model is a .env edit + `docker compose up -d`, never an image rebuild.
#
# Written only when OMP_MODEL_BASE_URL is set, so the file can also be managed
# by hand inside the state volume if you prefer.
# ---------------------------------------------------------------------------
if [ -n "${OMP_MODEL_BASE_URL:-}" ] && [ -n "${OMP_MODEL_ID:-}" ]; then
    provider="${OMP_MODEL_PROVIDER:-lan}"
    cat > "${AGENT_DIR}/models.yml" <<YAML
# Generated by omp-entrypoint on container start. Edits are overwritten.
# Source of truth is the .env next to docker-compose.yml.
providers:
  ${provider}:
    baseUrl: ${OMP_MODEL_BASE_URL}
    api: ${OMP_MODEL_API:-openai-completions}
    auth: none
    models:
      - id: ${OMP_MODEL_ID}
        name: ${OMP_MODEL_NAME:-${OMP_MODEL_ID}}
        reasoning: ${OMP_MODEL_REASONING:-false}
        input: [text]
        contextWindow: ${OMP_MODEL_CONTEXT:-131072}
        maxTokens: ${OMP_MODEL_MAX_TOKENS:-32768}
        cost:
          input: 0
          output: 0
          cacheRead: 0
          cacheWrite: 0
YAML
    log "wrote ${AGENT_DIR}/models.yml (${provider}/${OMP_MODEL_ID})"
fi

# ---------------------------------------------------------------------------
# tmux. The agent runs inside a detached session so that a dropped `docker exec`
# or ssh connection detaches instead of killing a run in progress.
# ---------------------------------------------------------------------------
if tmux has-session -t "$SESSION" 2>/dev/null; then
    log "tmux session '${SESSION}' already running"
else
    omp_cmd=(omp)
    [ -n "${OMP_MODEL:-}" ] && omp_cmd+=(--model "${OMP_MODEL}")
    # shellcheck disable=SC2206
    [ -n "${OMP_ARGS:-}" ] && omp_cmd+=(${OMP_ARGS})

    log "starting tmux session '${SESSION}': ${omp_cmd[*]}"
    tmux new-session -d -s "$SESSION" -n agent -c /workspace "${omp_cmd[@]}"
    # Leave a dead pane readable instead of collapsing the session (and with it
    # the container) the moment the agent exits.
    tmux set-option -t "$SESSION" remain-on-exit on
    tmux set-option -t "$SESSION" history-limit 50000
    tmux set-option -t "$SESSION" mouse on
    tmux new-window -t "$SESSION" -n shell -c /workspace
    tmux select-window -t "${SESSION}:agent"
fi

log "ready — attach with: docker compose exec ${OMP_NAME:-omp} tmux attach -t ${SESSION}"

# Block as PID 1. If the tmux server dies the client returns and the container
# exits, which is what `restart: unless-stopped` should react to.
exec tmux wait-for omp-shutdown
